package:
  name: autocnet
  version: 0.2.5
  
channels:
  - conda-forge
  - menpo
  - usgs-astrogeology
  
source:
   git_url: https://github.com/USGS-Astrogeology/autocnet.git
   git_rev: dev

requirements:
    build:
      - csmapi>=1.0.1
      - dill=0.3.2
      - geoalchemy2
      - geopandas=0.8.1
      - knoten>=0.2.1
      - networkx=2.4
      - opencv<=3.5
      - plio>=1.2.3
      - plurmy>=0.1.1
      - pysis>=0.1.1
      - pyyaml=5.3.1
      - redis-py
      - scikit-image=0.17.2
      - scipy=1.5.1
      - shapely=1.7.0
      - sqlalchemy-utils=0.36.6
    host:
      - python>=3
      - pip
    run:
      - csmapi
      - cyvlfeat
      - dill
      - geoalchemy2
      - geopandas
      - imageio
      - ipykernel
      - jupyter
      - knoten
      - ncurses
      - networkx
      - numpy
      - opencv<=3.5
      - pillow
      - plio>=1.1.0
      - plurmy
      - psycopg2
      - pvl<1.0.0
      - pyproj
      - pysis
      - pytest
      - pytest-cov
      - python>=3
      - pyyaml
      - redis-py
      - scikit-image
      - scikit-learn
      - scipy<=1.2.1
      - shapely
      - sqlalchemy
      - sqlalchemy-utils
      - usgscsm
      - vlfeat

test:
  imports:
    - autocnet
    - autocnet.graph.network
